project_id = "ljjgpiimryvfaoxpoqoy"

[functions.register]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-list-registrations]
verify_jwt = false

[functions.admin-update-registration]
verify_jwt = false

[functions.admin-email-template-get]
verify_jwt = false

[functions.admin-email-template-save]
verify_jwt = false

[functions.admin-email-send-test]
verify_jwt = false

[functions.admin-email-resend-confirmation]
verify_jwt = false

[functions.admin-generate-email]
verify_jwt = false

[functions.admin-send-broadcast]
verify_jwt = false

[functions.admin-campaigns-list]
verify_jwt = false

[functions.admin-campaign-get]
verify_jwt = false

[functions.admin-campaign-save]
verify_jwt = false
