// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljjgpiimryvfaoxpoqoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqamdwaWltcnl2ZmFveHBvcW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0Nzc1NDYsImV4cCI6MjA4NTA1MzU0Nn0.lp7s2xv4k9bxZbDxw_-MRqUKeEUWBwWuE39n75FPIwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});